language: scala
scala:
- 2.13.4
jdk:
  - openjdk8
before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt compile
    - name: run tests
      script: sbt test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
